//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliklinikaEntities : DbContext
    {
        public PoliklinikaEntities()
            : base("name=PoliklinikaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Врач> Врач { get; set; }
        public virtual DbSet<Время_приема> Время_приема { get; set; }
        public virtual DbSet<День_недели> День_недели { get; set; }
        public virtual DbSet<Диагноз> Диагноз { get; set; }
        public virtual DbSet<Запись_в_медкарте> Запись_в_медкарте { get; set; }
        public virtual DbSet<Кампания_выдав_Полиса> Кампания_выдав_Полиса { get; set; }
        public virtual DbSet<Категория_врача> Категория_врача { get; set; }
        public virtual DbSet<Мед__карта_пациента> Мед__карта_пациента { get; set; }
        public virtual DbSet<Отделение> Отделение { get; set; }
        public virtual DbSet<Пациенты> Пациенты { get; set; }
        public virtual DbSet<Пол> Пол { get; set; }
        public virtual DbSet<Полис_Пациента> Полис_Пациента { get; set; }
        public virtual DbSet<Специализация> Специализация { get; set; }
        public virtual DbSet<Специализация_врача> Специализация_врача { get; set; }
    }
}
