//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Время_приема
    {
        public int id_Времени { get; set; }
        public int id_записи_ { get; set; }
        public System.TimeSpan Время_приема1 { get; set; }
        public int id_Дня { get; set; }
        public int id_Пациента { get; set; }
    
        public virtual День_недели День_недели { get; set; }
        public virtual Специализация_врача Специализация_врача { get; set; }
        public virtual Пациенты Пациенты { get; set; }
    }
}
