//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Запись_в_медкарте
    {
        public int id_Записи { get; set; }
        public int id_Карты { get; set; }
        public int id_Врача { get; set; }
        public int id_Диагноза { get; set; }
        public string Назначения { get; set; }
    
        public virtual Врач Врач { get; set; }
        public virtual Диагноз Диагноз { get; set; }
        public virtual Мед__карта_пациента Мед__карта_пациента { get; set; }
    }
}
