//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poliklinika3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Полис_Пациента
    {
        public int id_Полиса_Запись { get; set; }
        public int id_Компании { get; set; }
        public System.DateTime Дата_выдачи { get; set; }
        public string Номер_полиса { get; set; }
    
        public virtual Кампания_выдав_Полиса Кампания_выдав_Полиса { get; set; }
        public virtual Пациенты Пациенты { get; set; }
    }
}
